fever = input('Have you been having fevers lately? (Y/N)\n').lower()
while fever != "y" or "n":
    fever = input('Have you been having fevers lately? (Y/N)\n').lower()
chills = input('Have you been having chills lately? (Y/N)\n').lower()
while chills != "y" or "n":
    chills = input('Have you been having chills lately? (Y/N)\n').lower()
shaking = input('Have you been having repeaated shaking lately? (Y/N)\n').lower()
while shaking != "y" or "n":
    shaking = input('Have you been having repeaated shaking lately? (Y/N)\n').lower()
muscle_pain = input('Have you been having muscle pain lately? (Y/N)\n').lower()
while muscle_pain != "y" or "n":
    muscle_pain = input('Have you been having muscle pain lately? (Y/N)\n').lower()
headache = input('Have you been having headaches lately? (Y/N)\n').lower()
while headache != "y" or "n":
    headache = input('Have you been having headaches lately? (Y/N)\n').lower()
sore_throat = input('Have you been having a sore throat lately? (Y/N)\n').lower()
while sore_throat != "y" or "n":
    sore_throat = input('Have you been having sore throat lately? (Y/N)\n').lower()
loss_taste_smell = input('Have you been having the loss of taste and/or smell lately? (Y/N)\n').lower()
while loss_taste_smell != "y" or "n":
    loss_taste_smell = input('Have you been having loss of taste and/or smell lately? (Y/N)\n').lower()
counts = {}
answers = [fever, chills, shaking, muscle_pain, headache, sore_throat, loss_taste_smell]