# Look at in fullscreen mode for best results

import turtle
# Setting up
gold = turtle.Turtle()
brown = turtle.Turtle()
wn = turtle.Screen()
wn.bgcolor("chocolate")
gold.color("gold")
gold.shape("turtle")
gold.pensize(5)
brown.color("brown")
brown.shape("turtle")
brown.pensize(5)
gold.speed(10)
brown.speed(10)
gold.penup()
gold.goto(0, -400)
brown.penup()
brown.goto(0, -500)
gold.pendown()
gold.left(90)
gold.forward(500)
brown.pendown()
brown.left(90)
brown.forward(100)
gold.right(10)
gold.forward(50)
gold.pensize(1)
gold.left(10)
gold.color("black")
gold.backward(550)
gold.forward(550)
gold.color("gold")
gold.right(10)
gold.pensize(5)
gold.color("silver")
gold.right(160)
gold.forward(50)
gold.right(10)
gold.forward(500)
brown.backward(100)
brown.right(90)
brown.forward(17)
brown.left(90)
brown.forward(100)
brown.left(90)
brown.forward(17)
brown.hideturtle()
gold.hideturtle()

wn.exitonclick()